Detached-anchors
diplodoc-platform/transform pull request #332
Opened 2023-11-13 12:22 UTC by main-kun

Add a plugin to support `{#my-anchor}` syntax for anchors detached from content

2023-11-14 14:48 UTC, moki requested changes

2023-11-14 14:48 UTC, moki commented on src/transform/plugins/detached-anchor/detached-anchor.ts
> +export const TOKEN_NAME = 'detached-anchor';
also let's name plugin block-anchor, anchor-block

2023-11-14 14:48 UTC, moki commented
let's go for the syntax: `{% anchor anchor-id %}`

regexp: `^{%[^\S\r\n]*anchor[^\S\r\n]+[\w-]+[^\S\r\n]*%}`

since we want to make leaf block node plugin, let's match only paragraphs with that syntax exclusively.

fair example would be:
https://github.com/diplodoc-platform/transform/blob/d0d26512d66c87b6179b5a75fb686f1ad081d360/src/transform/plugins/checkbox/checkbox.ts#L8-L14

2023-11-21 15:32 UTC, 3y3 commented on src/transform/plugins/block-anchor/block-anchor.ts
> +    return `<a id=${id}></a>`;
Это категорически невалидная разметка.
Ссылка без ссылки и без тайтла.

Почему это ссылка вообще?

2023-11-21 16:16 UTC, main-kun commented on src/transform/plugins/block-anchor/block-anchor.ts
> +    return `<a id=${id}></a>`;
Да, наверное не лучший элемент для якорей. Тогда сделаем пустой див?

2023-11-21 16:58 UTC, moki commented on src/transform/plugins/block-anchor/block-anchor.ts
> +    return `<a id=${id}></a>`;
я изначально предложил hr и мне кажется это норм варик

конечно же нужно будет завести css класс и написать стили.

2023-11-21 17:38 UTC, main-kun commented on src/transform/plugins/block-anchor/block-anchor.ts
> +function matchOpenToken(tokens: Token[], i: number) {
Сорри, забыл поменять.

2023-11-30 11:20 UTC, moki approved these changes

2023-11-30 11:34 UTC, merged